SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `codifiche` (
  `ID_CODIFICA` int(11) NOT NULL,
  `ID_SCHEMA` int(11) NOT NULL,
  `CODICE` varchar(255) NOT NULL,
  `DESCRIZIONE` varchar(255) NOT NULL,
  `UTENTE_CODIFICATORE` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `codifiche_dati` (
  `ID_CODIFICA` int(11) NOT NULL,
  `NOM_VARIABILE` varchar(20) NOT NULL,
  `ID_SCHEMA` int(11) NOT NULL,
  `VALORE` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `regole` (
  `ID_REGOLA` int(11) NOT NULL,
  `NOM_VARIABILE` varchar(20) NOT NULL,
  `GLOBAL` char(1) NOT NULL,
  `ETICHETTA` varchar(255) NOT NULL,
  `REQUIRED` char(1) NOT NULL,
  `TIPO` varchar(255) NOT NULL,
  `MAXLENGTH` int(11) DEFAULT NULL,
  `PATTERN_REGEXP` varchar(255) DEFAULT NULL,
  `NUM_DECIMALI` int(11) DEFAULT NULL,
  `MIN` double DEFAULT NULL,
  `MAX` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `regole_options` (
  `ID_REGOLA` int(11) NOT NULL,
  `VALUE_OPTION` varchar(255) NOT NULL,
  `ETICHETTA` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `regole_sottoschemi` (
  `ID_REGOLA` int(11) NOT NULL,
  `ID_SOTTO_SCHEMA` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `schemi_codifica` (
  `ID_SCHEMA` int(11) NOT NULL,
  `TITOLO` varchar(255) NOT NULL,
  `DESCRIZIONE` varchar(2000) NOT NULL,
  `TIPOLOGIA` char(1) NOT NULL,
  `TPL_CODICE` varchar(255) DEFAULT NULL,
  `TPL_DESCRIZIONE` varchar(2000) DEFAULT NULL,
  `PRE_RENDER_JS` varchar(2000) DEFAULT NULL,
  `IS_VALID` char(1) DEFAULT NULL,
  `IMMAGINE` blob DEFAULT NULL,
  `NOTE_INTERNE` varchar(2000) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `schemi_regole` (
  `ID_SCHEMA` int(11) NOT NULL,
  `NOM_VARIABILE` varchar(255) NOT NULL,
  `ID_REGOLA` int(11) NOT NULL,
  `ORD_PRESENTAZIONE` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE `codifiche`
  ADD PRIMARY KEY (`ID_CODIFICA`),
  ADD KEY `ID_SCHEMA` (`ID_SCHEMA`);

ALTER TABLE `codifiche_dati`
  ADD PRIMARY KEY (`ID_CODIFICA`,`NOM_VARIABILE`),
  ADD KEY `ID_SCHEMA` (`ID_SCHEMA`);

ALTER TABLE `regole`
  ADD PRIMARY KEY (`ID_REGOLA`),
  ADD KEY `ID_REGOLA` (`ID_REGOLA`);

ALTER TABLE `regole_options`
  ADD PRIMARY KEY (`ID_REGOLA`,`VALUE_OPTION`);

ALTER TABLE `regole_sottoschemi`
  ADD PRIMARY KEY (`ID_REGOLA`,`ID_SOTTO_SCHEMA`),
  ADD KEY `ID_SOTTO_SCHEMA` (`ID_SOTTO_SCHEMA`);

ALTER TABLE `schemi_codifica`
  ADD PRIMARY KEY (`ID_SCHEMA`);

ALTER TABLE `schemi_regole`
  ADD PRIMARY KEY (`ID_SCHEMA`,`NOM_VARIABILE`),
  ADD KEY `ID_REGOLA` (`ID_REGOLA`);


ALTER TABLE `codifiche`
  MODIFY `ID_CODIFICA` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `regole`
  MODIFY `ID_REGOLA` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `schemi_codifica`
  MODIFY `ID_SCHEMA` int(11) NOT NULL AUTO_INCREMENT;


ALTER TABLE `codifiche`
  ADD CONSTRAINT `codifiche_ibfk_1` FOREIGN KEY (`ID_SCHEMA`) REFERENCES `schemi_codifica` (`ID_SCHEMA`);

ALTER TABLE `codifiche_dati`
  ADD CONSTRAINT `codifiche_dati_ibfk_1` FOREIGN KEY (`ID_CODIFICA`) REFERENCES `codifiche` (`ID_CODIFICA`),
  ADD CONSTRAINT `codifiche_dati_ibfk_2` FOREIGN KEY (`ID_SCHEMA`) REFERENCES `schemi_codifica` (`ID_SCHEMA`);

ALTER TABLE `regole_options`
  ADD CONSTRAINT `regole_options_ibfk_1` FOREIGN KEY (`ID_REGOLA`) REFERENCES `regole` (`ID_REGOLA`);

ALTER TABLE `regole_sottoschemi`
  ADD CONSTRAINT `regole_sottoschemi_ibfk_1` FOREIGN KEY (`ID_SOTTO_SCHEMA`) REFERENCES `schemi_codifica` (`ID_SCHEMA`),
  ADD CONSTRAINT `regole_sottoschemi_ibfk_2` FOREIGN KEY (`ID_REGOLA`) REFERENCES `regole` (`ID_REGOLA`);

ALTER TABLE `schemi_regole`
  ADD CONSTRAINT `schemi_regole_ibfk_1` FOREIGN KEY (`ID_REGOLA`) REFERENCES `regole` (`ID_REGOLA`),
  ADD CONSTRAINT `schemi_regole_ibfk_2` FOREIGN KEY (`ID_SCHEMA`) REFERENCES `schemi_codifica` (`ID_SCHEMA`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
